// Versículos bíblicos diarios - Pancito de Vida
// 365 versículos (uno para cada día del año)

export interface Versiculo {
  texto: string;
  referencia: string;
}

export const versiculos: Versiculo[] = [
  // Enero (31 días)
  { texto: "Yo soy el pan de vida; el que a mí viene, nunca tendrá hambre.", referencia: "Juan 6:35" },
  { texto: "Dad, y se os dará; medida buena, apretada, remecida y rebosando.", referencia: "Lucas 6:38" },
  { texto: "El que comenzó en vosotros la buena obra, la perfeccionará.", referencia: "Filipenses 1:6" },
  { texto: "Todo lo puedo en Cristo que me fortalece.", referencia: "Filipenses 4:13" },
  { texto: "Jehová es mi pastor; nada me faltará.", referencia: "Salmos 23:1" },
  { texto: "Confía en Jehová de todo tu corazón, y no te apoyes en tu propia prudencia.", referencia: "Proverbios 3:5" },
  { texto: "El amor es sufrido, es benigno; el amor no tiene envidia.", referencia: "1 Corintios 13:4" },
  { texto: "Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito.", referencia: "Juan 3:16" },
  { texto: "Esfuérzate y sé valiente; no temas ni desmayes.", referencia: "Josué 1:9" },
  { texto: "Mas buscad primeramente el reino de Dios y su justicia.", referencia: "Mateo 6:33" },
  { texto: "La paz os dejo, mi paz os doy; no como el mundo la da.", referencia: "Juan 14:27" },
  { texto: "Venid a mí todos los que estáis trabajados y cargados.", referencia: "Mateo 11:28" },
  { texto: "Yo soy el camino, la verdad y la vida.", referencia: "Juan 14:6" },
  { texto: "El Señor es mi luz y mi salvación; ¿de quién temeré?", referencia: "Salmos 27:1" },
  { texto: "Bendito el hombre que confía en Jehová.", referencia: "Jeremías 17:7" },
  { texto: "Clama a mí, y yo te responderé.", referencia: "Jeremías 33:3" },
  { texto: "Jehová está cerca de los quebrantados de corazón.", referencia: "Salmos 34:18" },
  { texto: "Porque yo sé los pensamientos que tengo acerca de vosotros.", referencia: "Jeremías 29:11" },
  { texto: "El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente.", referencia: "Salmos 91:1" },
  { texto: "Por nada estéis afanosos, sino sean conocidas vuestras peticiones.", referencia: "Filipenses 4:6" },
  { texto: "Dios es amor; y el que permanece en amor, permanece en Dios.", referencia: "1 Juan 4:16" },
  { texto: "La fe es la certeza de lo que se espera, la convicción de lo que no se ve.", referencia: "Hebreos 11:1" },
  { texto: "Si Dios es por nosotros, ¿quién contra nosotros?", referencia: "Romanos 8:31" },
  { texto: "Aguarda a Jehová; esfuérzate, y aliéntese tu corazón.", referencia: "Salmos 27:14" },
  { texto: "En tu presencia hay plenitud de gozo.", referencia: "Salmos 16:11" },
  { texto: "Jesús le dijo: Yo soy la resurrección y la vida.", referencia: "Juan 11:25" },
  { texto: "Grande es Jehová, y digno de suprema alabanza.", referencia: "Salmos 48:1" },
  { texto: "Pedid, y se os dará; buscad, y hallaréis.", referencia: "Mateo 7:7" },
  { texto: "El justo por la fe vivirá.", referencia: "Romanos 1:17" },
  { texto: "Ninguna arma forjada contra ti prosperará.", referencia: "Isaías 54:17" },
  { texto: "El que da al pobre no tendrá pobreza.", referencia: "Proverbios 28:27" },
  
  // Febrero (28/29 días)
  { texto: "Mejor es lo poco con el temor de Jehová, que el gran tesoro donde hay turbación.", referencia: "Proverbios 15:16" },
  { texto: "Reconócelo en todos tus caminos, y él enderezará tus veredas.", referencia: "Proverbios 3:6" },
  { texto: "El que no ama, no ha conocido a Dios; porque Dios es amor.", referencia: "1 Juan 4:8" },
  { texto: "Cantad alegres a Dios, habitantes de toda la tierra.", referencia: "Salmos 100:1" },
  { texto: "El Señor es bueno; para siempre es su misericordia.", referencia: "Salmos 100:5" },
  { texto: "Sean vuestras costumbres sin avaricia, contentos con lo que tenéis ahora.", referencia: "Hebreos 13:5" },
  { texto: "Mas el fruto del Espíritu es amor, gozo, paz.", referencia: "Gálatas 5:22" },
  { texto: "Lámpara es a mis pies tu palabra, y lumbrera a mi camino.", referencia: "Salmos 119:105" },
  { texto: "Alegraos en el Señor siempre. Otra vez digo: ¡Alegraos!", referencia: "Filipenses 4:4" },
  { texto: "No os conforméis a este siglo, sino transformaos.", referencia: "Romanos 12:2" },
  { texto: "El que tiene misericordia de los pobres es bienaventurado.", referencia: "Proverbios 14:21" },
  { texto: "Echando toda vuestra ansiedad sobre él, porque él tiene cuidado de vosotros.", referencia: "1 Pedro 5:7" },
  { texto: "Bendice, alma mía, a Jehová, y no olvides ninguno de sus beneficios.", referencia: "Salmos 103:2" },
  { texto: "El nombre de Jehová es torre fuerte; a él correrá el justo, y será levantado.", referencia: "Proverbios 18:10" },
  { texto: "Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones.", referencia: "Salmos 46:1" },
  { texto: "Gustad, y ved que es bueno Jehová.", referencia: "Salmos 34:8" },
  { texto: "El Señor tu Dios está en medio de ti, poderoso, él salvará.", referencia: "Sofonías 3:17" },
  { texto: "Porque donde dos o tres se reúnen en mi nombre, allí estoy yo en medio de ellos.", referencia: "Mateo 18:20" },
  { texto: "Yo estoy con vosotros todos los días, hasta el fin del mundo.", referencia: "Mateo 28:20" },
  { texto: "Mi gracia te basta, porque mi poder se perfecciona en la debilidad.", referencia: "2 Corintios 12:9" },
  { texto: "Joven fui, y he envejecido, y no he visto justo desamparado.", referencia: "Salmos 37:25" },
  { texto: "Los que esperan a Jehová tendrán nuevas fuerzas.", referencia: "Isaías 40:31" },
  { texto: "Humillaos delante del Señor, y él os exaltará.", referencia: "Santiago 4:10" },
  { texto: "De gracia recibisteis, dad de gracia.", referencia: "Mateo 10:8" },
  { texto: "El que cree en mí, como dice la Escritura, de su interior correrán ríos de agua viva.", referencia: "Juan 7:38" },
  { texto: "Sean gratos los dichos de mi boca y la meditación de mi corazón delante de ti.", referencia: "Salmos 19:14" },
  { texto: "Porque donde está vuestro tesoro, allí estará también vuestro corazón.", referencia: "Mateo 6:21" },
  { texto: "Justicia y juicio son el cimiento de tu trono.", referencia: "Salmos 89:14" },
  
  // Marzo (31 días)
  { texto: "Instruye al niño en su camino, y aun cuando fuere viejo no se apartará de él.", referencia: "Proverbios 22:6" },
  { texto: "El que guarda su boca guarda su alma.", referencia: "Proverbios 13:3" },
  { texto: "El temor de Jehová es el principio de la sabiduría.", referencia: "Proverbios 9:10" },
  { texto: "Mas el que me oyere, habitará confiadamente y vivirá tranquilo, sin temor del mal.", referencia: "Proverbios 1:33" },
  { texto: "La esperanza que se demora es tormento del corazón.", referencia: "Proverbios 13:12" },
  { texto: "En toda labor hay fruto; mas las vanas palabras de los labios empobrecen.", referencia: "Proverbios 14:23" },
  { texto: "El que anda con sabios, sabio será.", referencia: "Proverbios 13:20" },
  { texto: "Mejor es la comida de legumbres donde hay amor, que de buey engordado donde hay odio.", referencia: "Proverbios 15:17" },
  { texto: "Del hombre son las disposiciones del corazón; mas de Jehová es la respuesta de la lengua.", referencia: "Proverbios 16:1" },
  { texto: "Mejor es morar en tierra desierta que con la mujer rencillosa e iracunda.", referencia: "Proverbios 21:19" },
  { texto: "No te jactes del día de mañana; porque no sabes qué dará de sí el día.", referencia: "Proverbios 27:1" },
  { texto: "El que encubre sus pecados no prosperará; mas el que los confiesa y se aparta alcanzará misericordia.", referencia: "Proverbios 28:13" },
  { texto: "El que confía en su propio corazón es necio.", referencia: "Proverbios 28:26" },
  { texto: "Donde no hay visión, el pueblo se extravía.", referencia: "Proverbios 29:18" },
  { texto: "Dad al Señor la honra debida a su nombre.", referencia: "Salmos 29:2" },
  { texto: "Espera en Jehová, y guarda su camino.", referencia: "Salmos 37:34" },
  { texto: "Crea en mí, oh Dios, un corazón limpio, y renueva un espíritu recto dentro de mí.", referencia: "Salmos 51:10" },
  { texto: "Porque mejor es un día en tus atrios que mil fuera de ellos.", referencia: "Salmos 84:10" },
  { texto: "Bueno es Jehová para con todos, y sus misericordias sobre todas sus obras.", referencia: "Salmos 145:9" },
  { texto: "Jehová guarda a todos los que le aman.", referencia: "Salmos 145:20" },
  { texto: "Alabad a Jehová, porque él es bueno; porque para siempre es su misericordia.", referencia: "Salmos 136:1" },
  { texto: "Si Jehová no edificare la casa, en vano trabajan los que la edifican.", referencia: "Salmos 127:1" },
  { texto: "Los que siembran con lágrimas, con regocijo segarán.", referencia: "Salmos 126:5" },
  { texto: "Con Jehová están los orígenes de la vida.", referencia: "Salmos 36:9" },
  { texto: "Delante de Jehová está el Seol y el Abadón; ¿cuánto más los corazones de los hombres?", referencia: "Proverbios 15:11" },
  { texto: "La lengua apacible es árbol de vida; mas la perversidad de ella es quebrantamiento de espíritu.", referencia: "Proverbios 15:4" },
  { texto: "El corazón alegre hermosea el rostro; mas por el dolor del corazón el espíritu se abate.", referencia: "Proverbios 15:13" },
  { texto: "Panal de miel son los dichos suaves; suavidad al alma y medicina para los huesos.", referencia: "Proverbios 16:24" },
  { texto: "Mejor es el que tarda en airarse que el fuerte.", referencia: "Proverbios 16:32" },
  { texto: "Las canas son corona de honra cuando se hallan en el camino de justicia.", referencia: "Proverbios 16:31" },
  { texto: "Muchos pensamientos hay en el corazón del hombre; mas el consejo de Jehová permanecerá.", referencia: "Proverbios 19:21" },
  
  // Abril (30 días)
  { texto: "El buen nombre es mejor que las muchas riquezas.", referencia: "Proverbios 22:1" },
  { texto: "No te entremetas con el iracundo, ni te acompañes con el hombre de enojos.", referencia: "Proverbios 22:24" },
  { texto: "Cuando te sientes a comer con algún señor, considera bien lo que está delante de ti.", referencia: "Proverbios 23:1" },
  { texto: "No hables a oídos del necio, porque menospreciará la prudencia de tus razones.", referencia: "Proverbios 23:9" },
  { texto: "Mejor es el pobre que camina en integridad que el de perversos caminos y rico.", referencia: "Proverbios 28:6" },
  { texto: "El que aparta su oído para no oír la ley, su oración también es abominable.", referencia: "Proverbios 28:9" },
  { texto: "El que aumenta sus riquezas con usura y crecido interés, para aquel que se compadece de los pobres las aumenta.", referencia: "Proverbios 28:8" },
  { texto: "El alma generosa será prosperada; y el que saciare, él también será saciado.", referencia: "Proverbios 11:25" },
  { texto: "Con sabiduría se edificará la casa, y con prudencia se afirmará.", referencia: "Proverbios 24:3" },
  { texto: "No digas: Como me hizo, así le haré; daré el pago al hombre según su obra.", referencia: "Proverbios 24:29" },
  { texto: "Como ciudad derribada y sin muro es el hombre cuyo espíritu no tiene rienda.", referencia: "Proverbios 25:28" },
  { texto: "El que odia disimula con sus labios; mas en su interior maquina engaño.", referencia: "Proverbios 26:24" },
  { texto: "Fiel es el Señor, que os afirmará y guardará del mal.", referencia: "2 Tesalonicenses 3:3" },
  { texto: "Desecha de ti la perversidad de la boca, y aleja de ti la iniquidad de labios.", referencia: "Proverbios 4:24" },
  { texto: "Sobre toda cosa guardada, guarda tu corazón; porque de él mana la vida.", referencia: "Proverbios 4:23" },
  { texto: "La senda de los justos es como la luz de la aurora, que va en aumento hasta que el día es perfecto.", referencia: "Proverbios 4:18" },
  { texto: "Hijo mío, está atento a mis palabras; inclina tu oído a mis razones.", referencia: "Proverbios 4:20" },
  { texto: "Porque el mandamiento es lámpara, y la enseñanza es luz.", referencia: "Proverbios 6:23" },
  { texto: "Seis cosas aborrece Jehová, y aun siete abomina su alma.", referencia: "Proverbios 6:16" },
  { texto: "Los labios del necio traen contienda; y su boca los azotes llama.", referencia: "Proverbios 18:6" },
  { texto: "La muerte y la vida están en poder de la lengua.", referencia: "Proverbios 18:21" },
  { texto: "El hombre que tiene amigos ha de mostrarse amigo.", referencia: "Proverbios 18:24" },
  { texto: "La mujer virtuosa es corona de su marido.", referencia: "Proverbios 12:4" },
  { texto: "En la casa del justo hay gran provisión.", referencia: "Proverbios 15:6" },
  { texto: "El que perdona la ofensa cultiva el amor.", referencia: "Proverbios 17:9" },
  { texto: "Aun el muchacho es conocido por sus hechos, si su conducta fuere limpia y recta.", referencia: "Proverbios 20:11" },
  { texto: "Tesoro precioso y aceite hay en la casa del sabio.", referencia: "Proverbios 21:20" },
  { texto: "El que sigue la justicia y la misericordia hallará la vida, la justicia y la honra.", referencia: "Proverbios 21:21" },
  { texto: "No envidies a los hombres malos, ni desees estar con ellos.", referencia: "Proverbios 24:1" },
  { texto: "El perezoso dice: El león está fuera; seré muerto en la calle.", referencia: "Proverbios 22:13" },
  
  // Mayo (31 días)
  { texto: "No te alabes delante del rey, ni estés en el lugar de los grandes.", referencia: "Proverbios 25:6" },
  { texto: "Como manzana de oro con figuras de plata es la palabra dicha como conviene.", referencia: "Proverbios 25:11" },
  { texto: "Con larga paciencia se aplaca el príncipe.", referencia: "Proverbios 25:15" },
  { texto: "¿Hallaste miel? Come lo que te basta, no sea que hastiado de ella la vomites.", referencia: "Proverbios 25:16" },
  { texto: "El que canta canciones al corazón afligido es como el que quita la ropa en tiempo de frío.", referencia: "Proverbios 25:20" },
  { texto: "Si el que te aborrece tuviere hambre, dale de comer pan.", referencia: "Proverbios 25:21" },
  { texto: "Como perro que vuelve a su vómito, así es el necio que repite su necedad.", referencia: "Proverbios 26:11" },
  { texto: "Déjate alabar del extraño, y no de tu boca.", referencia: "Proverbios 27:2" },
  { texto: "El hierro con hierro se aguza; y así el hombre aguza el rostro de su amigo.", referencia: "Proverbios 27:17" },
  { texto: "Mejor es reprensión manifiesta que amor oculto.", referencia: "Proverbios 27:5" },
  { texto: "Como el ave que se va de su nido, así es el hombre que se va de su lugar.", referencia: "Proverbios 27:8" },
  { texto: "El perfume y el incienso alegran el corazón.", referencia: "Proverbios 27:9" },
  { texto: "No abandones a tu amigo, ni al amigo de tu padre.", referencia: "Proverbios 27:10" },
  { texto: "Hijo mío, sé sabio, y alegra mi corazón.", referencia: "Proverbios 27:11" },
  { texto: "El avisado ve el mal y se esconde; mas los simples pasan y reciben el daño.", referencia: "Proverbios 27:12" },
  { texto: "Como en el agua el rostro corresponde al rostro, así el corazón del hombre al del hombre.", referencia: "Proverbios 27:19" },
  { texto: "Conoce bien la condición de tus ovejas, y mira con cuidado por tus rebaños.", referencia: "Proverbios 27:23" },
  { texto: "Huye el impío sin que nadie lo persiga; mas el justo está confiado como un león.", referencia: "Proverbios 28:1" },
  { texto: "El hombre de verdad tendrá muchas bendiciones.", referencia: "Proverbios 28:20" },
  { texto: "El que endurece su cerviz será quebrantado de repente sin remedio.", referencia: "Proverbios 29:1" },
  { texto: "Cuando los justos dominan, el pueblo se alegra.", referencia: "Proverbios 29:2" },
  { texto: "El hombre que lisonjea a su prójimo red tiende delante de sus pasos.", referencia: "Proverbios 29:5" },
  { texto: "El que reprehende al hombre, hallará después mayor gracia que el que lisonjea.", referencia: "Proverbios 28:23" },
  { texto: "El que hurta a su padre o a su madre, y dice que no es maldad, compañero es del hombre destruidor.", referencia: "Proverbios 28:24" },
  { texto: "Bienaventurado el hombre que siempre teme a Dios.", referencia: "Proverbios 28:14" },
  { texto: "El que confiesa y se aparta alcanzará misericordia.", referencia: "Proverbios 28:13" },
  { texto: "Los justos se interesan en la causa de los pobres.", referencia: "Proverbios 29:7" },
  { texto: "El necio da rienda suelta a toda su ira, mas el sabio al fin la sosiega.", referencia: "Proverbios 29:11" },
  { texto: "La vara y la corrección dan sabiduría; mas el muchacho consentido avergonzará a su madre.", referencia: "Proverbios 29:15" },
  { texto: "Corrige a tu hijo, y te dará descanso, y dará alegría a tu alma.", referencia: "Proverbios 29:17" },
  { texto: "Sin profecía el pueblo se desenfrena.", referencia: "Proverbios 29:18" },
  
  // Junio (30 días)
  { texto: "¿Has visto hombre solícito en su trabajo? Delante de los reyes estará.", referencia: "Proverbios 22:29" },
  { texto: "Toda palabra de Dios es limpia; él es escudo a los que en él esperan.", referencia: "Proverbios 30:5" },
  { texto: "No añadas a sus palabras, para que no te reprenda, y seas hallado mentiroso.", referencia: "Proverbios 30:6" },
  { texto: "Dos cosas te he demandado; no me las niegues antes que muera.", referencia: "Proverbios 30:7" },
  { texto: "Vanidad y palabra mentirosa aparta de mí; no me des pobreza ni riquezas.", referencia: "Proverbios 30:8" },
  { texto: "Susténtame del pan necesario; no sea que me sacie, y te niegue.", referencia: "Proverbios 30:8-9" },
  { texto: "La sanguijuela tiene dos hijas que dicen: ¡Dame! ¡Dame!", referencia: "Proverbios 30:15" },
  { texto: "Tres cosas me son ocultas; aun la cuarta no entiendo.", referencia: "Proverbios 30:18" },
  { texto: "Por tres cosas se alborota la tierra, y la cuarta ella no puede sufrir.", referencia: "Proverbios 30:21" },
  { texto: "Cuatro cosas son de las más pequeñas de la tierra, y las mismas son más sabias que los sabios.", referencia: "Proverbios 30:24" },
  { texto: "Tres cosas hay de hermoso andar, y la cuarta pasea muy bien.", referencia: "Proverbios 30:29" },
  { texto: "Abre tu boca por el mudo en el juicio de todos los desvalidos.", referencia: "Proverbios 31:8" },
  { texto: "Abre tu boca, juzga con justicia, y defiende la causa del pobre y del menesteroso.", referencia: "Proverbios 31:9" },
  { texto: "Mujer virtuosa, ¿quién la hallará? Porque su estima sobrepasa largamente a la de las piedras preciosas.", referencia: "Proverbios 31:10" },
  { texto: "El corazón de su marido está en ella confiado.", referencia: "Proverbios 31:11" },
  { texto: "Le da ella bien y no mal todos los días de su vida.", referencia: "Proverbios 31:12" },
  { texto: "Se levanta aun de noche y da comida a su familia.", referencia: "Proverbios 31:15" },
  { texto: "Considera la heredad, y la compra, y planta viña del fruto de sus manos.", referencia: "Proverbios 31:16" },
  { texto: "Ciñe de fuerza sus lomos, y esfuerza sus brazos.", referencia: "Proverbios 31:17" },
  { texto: "Alarga su mano al pobre, y extiende sus manos al menesteroso.", referencia: "Proverbios 31:20" },
  { texto: "Fuerza y honor son su vestidura; y se ríe de lo por venir.", referencia: "Proverbios 31:25" },
  { texto: "Abre su boca con sabiduría, y la ley de clemencia está en su lengua.", referencia: "Proverbios 31:26" },
  { texto: "Se levantan sus hijos y la llaman bienaventurada.", referencia: "Proverbios 31:28" },
  { texto: "Engañosa es la gracia, y vana la hermosura; la mujer que teme a Jehová, ésa será alabada.", referencia: "Proverbios 31:30" },
  { texto: "Dadle del fruto de sus manos, y alábenla en las puertas sus hechos.", referencia: "Proverbios 31:31" },
  { texto: "Jehová de los ejércitos está con nosotros; nuestro refugio es el Dios de Jacob.", referencia: "Salmos 46:11" },
  { texto: "Estad quietos, y conoced que yo soy Dios.", referencia: "Salmos 46:10" },
  { texto: "Aclamad a Dios con voz de júbilo.", referencia: "Salmos 47:1" },
  { texto: "Dios es el Rey de toda la tierra; cantad con inteligencia.", referencia: "Salmos 47:7" },
  { texto: "Grande es Jehová, y digno de ser en gran manera alabado.", referencia: "Salmos 48:1" },
  
  // Julio (31 días)
  { texto: "Como se alegra el monte de Sion se alegran las hijas de Judá.", referencia: "Salmos 48:11" },
  { texto: "Ninguno de ellos podrá en manera alguna redimir al hermano.", referencia: "Salmos 49:7" },
  { texto: "Mas Dios redimirá mi vida del poder del Seol.", referencia: "Salmos 49:15" },
  { texto: "El Dios de dioses, Jehová, ha hablado, y convocado la tierra.", referencia: "Salmos 50:1" },
  { texto: "Invócame en el día de la angustia; te libraré, y tú me honrarás.", referencia: "Salmos 50:15" },
  { texto: "Ofrece a Dios alabanza, y paga tus votos al Altísimo.", referencia: "Salmos 50:14" },
  { texto: "Ten piedad de mí, oh Dios, conforme a tu misericordia.", referencia: "Salmos 51:1" },
  { texto: "Contra ti, contra ti solo he pecado, y he hecho lo malo delante de tus ojos.", referencia: "Salmos 51:4" },
  { texto: "He aquí, en maldad he sido formado, y en pecado me concibió mi madre.", referencia: "Salmos 51:5" },
  { texto: "Purifícame con hisopo, y seré limpio; lávame, y seré más blanco que la nieve.", referencia: "Salmos 51:7" },
  { texto: "No me eches de delante de ti, y no quites de mí tu santo Espíritu.", referencia: "Salmos 51:11" },
  { texto: "Vuélveme el gozo de tu salvación, y espíritu noble me sustente.", referencia: "Salmos 51:12" },
  { texto: "Los sacrificios de Dios son el espíritu quebrantado.", referencia: "Salmos 51:17" },
  { texto: "Echa sobre Jehová tu carga, y él te sustentará.", referencia: "Salmos 55:22" },
  { texto: "En Dios he confiado; no temeré lo que me pueda hacer el hombre.", referencia: "Salmos 56:11" },
  { texto: "Ten misericordia de mí, oh Dios, ten misericordia de mí; porque en ti ha confiado mi alma.", referencia: "Salmos 57:1" },
  { texto: "Despierta, alma mía; despertad, salterio y arpa; despertaré al alba.", referencia: "Salmos 57:8" },
  { texto: "Porque grande es hasta los cielos tu misericordia.", referencia: "Salmos 57:10" },
  { texto: "Ciertamente vanidad son los hijos de los hombres, mentira los hijos de varón.", referencia: "Salmos 62:9" },
  { texto: "En Dios solamente está acallada mi alma; de él viene mi salvación.", referencia: "Salmos 62:1" },
  { texto: "Una vez habló Dios; dos veces he oído esto: Que de Dios es el poder.", referencia: "Salmos 62:11" },
  { texto: "Oh Dios, Dios mío eres tú; de madrugada te buscaré.", referencia: "Salmos 63:1" },
  { texto: "Porque mejor es tu misericordia que la vida; mis labios te alabarán.", referencia: "Salmos 63:3" },
  { texto: "Así te bendeciré en mi vida; en tu nombre alzaré mis manos.", referencia: "Salmos 63:4" },
  { texto: "Cuando me acuerde de ti en mi lecho, cuando medite en ti en las vigilias de la noche.", referencia: "Salmos 63:6" },
  { texto: "Tuyo, oh Dios, es el poder; tuya, oh Señor, es la misericordia.", referencia: "Salmos 62:11-12" },
  { texto: "Venid, oíd todos los que teméis a Dios, y contaré lo que ha hecho a mi alma.", referencia: "Salmos 66:16" },
  { texto: "Bendito sea Dios, que no echó de sí mi oración, ni de mí su misericordia.", referencia: "Salmos 66:20" },
  { texto: "Dios tenga misericordia de nosotros, y nos bendiga.", referencia: "Salmos 67:1" },
  { texto: "Alégrense y gócense las naciones, porque juzgarás los pueblos con equidad.", referencia: "Salmos 67:4" },
  { texto: "Levántese Dios, sean esparcidos sus enemigos.", referencia: "Salmos 68:1" },
  
  // Agosto (31 días)
  { texto: "Padre de huérfanos y defensor de viudas es Dios en su santa morada.", referencia: "Salmos 68:5" },
  { texto: "Dios hace habitar en familia a los desamparados.", referencia: "Salmos 68:6" },
  { texto: "Bendito el Señor; cada día nos colma de beneficios.", referencia: "Salmos 68:19" },
  { texto: "El Dios nuestro, Dios de salvación; de Jehová el Señor es el librar de la muerte.", referencia: "Salmos 68:20" },
  { texto: "Canten a Dios, reinos de la tierra, canten al Señor.", referencia: "Salmos 68:32" },
  { texto: "Sálvame, oh Dios, porque las aguas han entrado hasta el alma.", referencia: "Salmos 69:1" },
  { texto: "Estoy hundido en cieno profundo, donde no puedo hacer pie.", referencia: "Salmos 69:2" },
  { texto: "Respóndeme, Jehová, porque benigna es tu misericordia.", referencia: "Salmos 69:16" },
  { texto: "Tú conoces mi afrenta, mi confusión y mi oprobio.", referencia: "Salmos 69:19" },
  { texto: "Sean tus ojos sobre mí para bien; vuélvete a mí, y ten misericordia de mí.", referencia: "Salmos 69:16" },
  { texto: "Oh Dios, acude a librarme; apresúrate, oh Dios, a socorrerme.", referencia: "Salmos 70:1" },
  { texto: "Busquen a Dios todos los que te aman, y digan siempre: Engrandecido sea Dios.", referencia: "Salmos 70:4" },
  { texto: "En ti, oh Jehová, he esperado; no sea yo confundido jamás.", referencia: "Salmos 71:1" },
  { texto: "Tú eres mi esperanza, Señor Jehová, mi confianza desde mi juventud.", referencia: "Salmos 71:5" },
  { texto: "Sea llena mi boca de tu alabanza, de tu gloria todo el día.", referencia: "Salmos 71:8" },
  { texto: "No me deseches en el tiempo de la vejez; cuando mi fuerza se acabare, no me desampares.", referencia: "Salmos 71:9" },
  { texto: "Oh Dios, me enseñaste desde mi juventud, y hasta ahora he manifestado tus maravillas.", referencia: "Salmos 71:17" },
  { texto: "Dará el rey tus juicios, oh Dios, y tu justicia al hijo del rey.", referencia: "Salmos 72:1" },
  { texto: "Juzgará a los afligidos del pueblo, salvará a los hijos del menesteroso.", referencia: "Salmos 72:4" },
  { texto: "Descenderá como la lluvia sobre la hierba cortada.", referencia: "Salmos 72:6" },
  { texto: "Florecerá en sus días justicia, y muchedumbre de paz, hasta que no haya luna.", referencia: "Salmos 72:7" },
  { texto: "Dominará de mar a mar, y desde el río hasta los confines de la tierra.", referencia: "Salmos 72:8" },
  { texto: "Los reyes de Tarsis y de las costas traerán presentes.", referencia: "Salmos 72:10" },
  { texto: "Porque él librará al menesteroso que clamare, y al afligido que no tuviere quien le socorra.", referencia: "Salmos 72:12" },
  { texto: "Tendrá misericordia del pobre y del menesteroso, y salvará la vida de los pobres.", referencia: "Salmos 72:13" },
  { texto: "Será su nombre para siempre, se perpetuará su nombre mientras dure el sol.", referencia: "Salmos 72:17" },
  { texto: "Bendito Jehová Dios, el Dios de Israel, el único que hace maravillas.", referencia: "Salmos 72:18" },
  { texto: "En cuanto a mí, el acercarme a Dios es el bien.", referencia: "Salmos 73:28" },
  { texto: "¿Por qué, oh Dios, nos has desechado para siempre?", referencia: "Salmos 74:1" },
  { texto: "Acuérdate de tu congregación, la que adquiriste desde tiempos antiguos.", referencia: "Salmos 74:2" },
  { texto: "Tuyo es el día, tuya también es la noche; tú estableciste la luna y el sol.", referencia: "Salmos 74:16" },
  
  // Septiembre (30 días)
  { texto: "Gracias te damos, oh Dios, gracias te damos, pues cercano está tu nombre.", referencia: "Salmos 75:1" },
  { texto: "Porque ni de oriente ni de occidente, ni del desierto viene el enaltecimiento.", referencia: "Salmos 75:6" },
  { texto: "Mas Dios es el juez; a éste humilla, y a aquél enaltece.", referencia: "Salmos 75:7" },
  { texto: "Dios es conocido en Judá; en Israel es grande su nombre.", referencia: "Salmos 76:1" },
  { texto: "En Salem está su tabernáculo, y su habitación en Sion.", referencia: "Salmos 76:2" },
  { texto: "Glorioso eres tú, poderoso más que los montes de caza.", referencia: "Salmos 76:4" },
  { texto: "Tú, temible eres tú; ¿y quién podrá estar en pie delante de ti cuando se encienda tu ira?", referencia: "Salmos 76:7" },
  { texto: "Conocido es en Judá Dios; su nombre es grande en Israel.", referencia: "Salmos 76:1" },
  { texto: "Con mi voz clamé a Dios, a Dios clamé, y él me escuchará.", referencia: "Salmos 77:1" },
  { texto: "¿Ha cesado para siempre su misericordia? ¿Se ha acabado perpetuamente su promesa?", referencia: "Salmos 77:8" },
  { texto: "Me acordaré de las obras de JAH; sí, haré yo memoria de tus maravillas antiguas.", referencia: "Salmos 77:11" },
  { texto: "Oh Dios, santo es tu camino; ¿qué dios es grande como nuestro Dios?", referencia: "Salmos 77:13" },
  { texto: "Tú eres el Dios que hace maravillas; hiciste notorio en los pueblos tu poder.", referencia: "Salmos 77:14" },
  { texto: "Escucha, pueblo mío, mi ley; inclinad vuestro oído a las palabras de mi boca.", referencia: "Salmos 78:1" },
  { texto: "Abriré mi boca en proverbios; hablaré cosas escondidas desde tiempos antiguos.", referencia: "Salmos 78:2" },
  { texto: "Las cuales hemos oído y entendido; que nuestros padres nos las contaron.", referencia: "Salmos 78:3" },
  { texto: "No las encubriremos a sus hijos, contando a la generación venidera las alabanzas de Jehová.", referencia: "Salmos 78:4" },
  { texto: "Estableció testimonio en Jacob, y puso ley en Israel.", referencia: "Salmos 78:5" },
  { texto: "Para que lo sepa la generación venidera, y los hijos que nacerán.", referencia: "Salmos 78:6" },
  { texto: "A fin de que pongan en Dios su confianza, y no se olviden de las obras de Dios.", referencia: "Salmos 78:7" },
  { texto: "Y no sean como sus padres, generación contumaz y rebelde.", referencia: "Salmos 78:8" },
  { texto: "Oh Dios, vinieron las naciones a tu heredad; han profanado tu santo templo.", referencia: "Salmos 79:1" },
  { texto: "Redújeron a Jerusalén a montones de ruinas.", referencia: "Salmos 79:1" },
  { texto: "Ayúdanos, oh Dios de nuestra salvación, por la gloria de tu nombre.", referencia: "Salmos 79:9" },
  { texto: "Líbranos, y perdona nuestros pecados por amor de tu nombre.", referencia: "Salmos 79:9" },
  { texto: "Oh Pastor de Israel, escucha; tú que pastoreas como a ovejas a José.", referencia: "Salmos 80:1" },
  { texto: "Despierta tu poder, y ven a salvarnos.", referencia: "Salmos 80:2" },
  { texto: "Oh Jehová, Dios de los ejércitos, restáuranos; haz resplandecer tu rostro, y seremos salvos.", referencia: "Salmos 80:3" },
  { texto: "Hiciste venir una vid de Egipto; echaste las naciones, y la plantaste.", referencia: "Salmos 80:8" },
  { texto: "Vuélvete ahora, oh Dios de los ejércitos; mira desde el cielo, y considera, y visita esta viña.", referencia: "Salmos 80:14" },
  
  // Octubre (31 días)
  { texto: "Cantad con gozo a Dios, fortaleza nuestra; al Dios de Jacob aclamad con júbilo.", referencia: "Salmos 81:1" },
  { texto: "Entonad canción, y tañed el pandero, el arpa deliciosa y el salterio.", referencia: "Salmos 81:2" },
  { texto: "Tocad la trompeta en la nueva luna, en el día señalado, en el día de nuestra fiesta solemne.", referencia: "Salmos 81:3" },
  { texto: "Porque estatuto es de Israel, ordenanza del Dios de Jacob.", referencia: "Salmos 81:4" },
  { texto: "Yo soy Jehová tu Dios, que te hice subir de la tierra de Egipto.", referencia: "Salmos 81:10" },
  { texto: "Abre tu boca, y yo la llenaré.", referencia: "Salmos 81:10" },
  { texto: "Oh, si me hubiera oído mi pueblo, si en mis caminos hubiera andado Israel.", referencia: "Salmos 81:13" },
  { texto: "En un momento habría yo derribado a sus enemigos.", referencia: "Salmos 81:14" },
  { texto: "Los que aborrecen a Jehová se le habrían sometido.", referencia: "Salmos 81:15" },
  { texto: "Dios está en la reunión de los dioses; en medio de los dioses juzga.", referencia: "Salmos 82:1" },
  { texto: "¿Hasta cuándo juzgaréis injustamente, y aceptaréis las personas de los impíos?", referencia: "Salmos 82:2" },
  { texto: "Defended al débil y al huérfano; haced justicia al afligido y al menesteroso.", referencia: "Salmos 82:3" },
  { texto: "Librad al afligido y al necesitado; libradlo de mano de los impíos.", referencia: "Salmos 82:4" },
  { texto: "Yo dije: Vosotros sois dioses, y todos vosotros hijos del Altísimo.", referencia: "Salmos 82:6" },
  { texto: "Oh Dios, no guardes silencio; no calles, oh Dios, ni te estés quieto.", referencia: "Salmos 83:1" },
  { texto: "Porque he aquí que rugen tus enemigos, y los que te aborrecen alzan cabeza.", referencia: "Salmos 83:2" },
  { texto: "Contra tu pueblo han consultado astuta y secretamente.", referencia: "Salmos 83:3" },
  { texto: "Han dicho: Venid, y destruyámoslos para que no sean nación.", referencia: "Salmos 83:4" },
  { texto: "Sean afrentados y turbados para siempre; sean deshonrados, y perezcan.", referencia: "Salmos 83:17" },
  { texto: "Y conozcan que tu nombre es JEHOVÁ; tú solo Altísimo sobre toda la tierra.", referencia: "Salmos 83:18" },
  { texto: "¡Cuán amables son tus moradas, oh Jehová de los ejércitos!", referencia: "Salmos 84:1" },
  { texto: "Anhela mi alma y aun ardientemente desea los atrios de Jehová.", referencia: "Salmos 84:2" },
  { texto: "Aun el gorrión halla casa, y la golondrina nido para sí.", referencia: "Salmos 84:3" },
  { texto: "Bienaventurados los que habitan en tu casa; perpetuamente te alabarán.", referencia: "Salmos 84:4" },
  { texto: "Bienaventurado el hombre que tiene en ti sus fuerzas.", referencia: "Salmos 84:5" },
  { texto: "Atravesando el valle de lágrimas lo cambian en fuente.", referencia: "Salmos 84:6" },
  { texto: "Irán de poder en poder; verán a Dios en Sion.", referencia: "Salmos 84:7" },
  { texto: "Jehová de los ejércitos, oye mi oración; escucha, oh Dios de Jacob.", referencia: "Salmos 84:8" },
  { texto: "Mira, oh Dios, escudo nuestro, y pon los ojos en el rostro de tu ungido.", referencia: "Salmos 84:9" },
  { texto: "Escogería antes estar a la puerta de la casa de mi Dios, que habitar en las moradas de maldad.", referencia: "Salmos 84:10" },
  { texto: "Porque sol y escudo es Jehová Dios; gracia y gloria dará Jehová.", referencia: "Salmos 84:11" },
  
  // Noviembre (30 días)
  { texto: "No quitará el bien a los que andan en integridad.", referencia: "Salmos 84:11" },
  { texto: "Jehová de los ejércitos, dichoso el hombre que en ti confía.", referencia: "Salmos 84:12" },
  { texto: "Fuiste propicio a tu tierra, oh Jehová; volviste la cautividad de Jacob.", referencia: "Salmos 85:1" },
  { texto: "Perdonaste la iniquidad de tu pueblo; todos los pecados de ellos cubriste.", referencia: "Salmos 85:2" },
  { texto: "Reprimiste todo tu enojo; te apartaste del ardor de tu ira.", referencia: "Salmos 85:3" },
  { texto: "Restáuranos, oh Dios de nuestra salvación, y haz cesar tu ira de sobre nosotros.", referencia: "Salmos 85:4" },
  { texto: "¿Estarás enojado contra nosotros para siempre?", referencia: "Salmos 85:5" },
  { texto: "¿No volverás a darnos vida, para que tu pueblo se regocije en ti?", referencia: "Salmos 85:6" },
  { texto: "Muéstranos, oh Jehová, tu misericordia, y danos tu salvación.", referencia: "Salmos 85:7" },
  { texto: "Escucharé lo que hablará Jehová Dios; porque hablará paz a su pueblo.", referencia: "Salmos 85:8" },
  { texto: "Ciertamente cercana está su salvación a los que le temen.", referencia: "Salmos 85:9" },
  { texto: "La misericordia y la verdad se encontraron; la justicia y la paz se besaron.", referencia: "Salmos 85:10" },
  { texto: "La verdad brotará de la tierra, y la justicia mirará desde los cielos.", referencia: "Salmos 85:11" },
  { texto: "Jehová dará también el bien, y nuestra tierra dará su fruto.", referencia: "Salmos 85:12" },
  { texto: "Inclina, oh Jehová, tu oído, y escúchame, porque estoy afligido y menesteroso.", referencia: "Salmos 86:1" },
  { texto: "Guarda mi alma, porque soy piadoso; salva tú, oh Dios mío, a tu siervo que en ti confía.", referencia: "Salmos 86:2" },
  { texto: "Ten misericordia de mí, oh Jehová; porque a ti clamo todo el día.", referencia: "Salmos 86:3" },
  { texto: "Alegra el alma de tu siervo, porque a ti, oh Señor, levanto mi alma.", referencia: "Salmos 86:4" },
  { texto: "Porque tú, Señor, eres bueno y perdonador, y grande en misericordia.", referencia: "Salmos 86:5" },
  { texto: "Escucha, oh Jehová, mi oración, y está atento a la voz de mis ruegos.", referencia: "Salmos 86:6" },
  { texto: "En el día de mi angustia te llamaré, porque tú me respondes.", referencia: "Salmos 86:7" },
  { texto: "Oh Señor, no hay como tú entre los dioses, ni obras que igualen tus obras.", referencia: "Salmos 86:8" },
  { texto: "Todas las naciones que hiciste vendrán y adorarán delante de ti, Señor.", referencia: "Salmos 86:9" },
  { texto: "Porque tú eres grande, y hacedor de maravillas; sólo tú eres Dios.", referencia: "Salmos 86:10" },
  { texto: "Enséñame, oh Jehová, tu camino; caminaré yo en tu verdad.", referencia: "Salmos 86:11" },
  { texto: "Afirma mi corazón para que tema tu nombre.", referencia: "Salmos 86:11" },
  { texto: "Te alabaré, oh Jehová Dios mío, con todo mi corazón.", referencia: "Salmos 86:12" },
  { texto: "Porque tu misericordia es grande para conmigo, y has librado mi alma de las profundidades del Seol.", referencia: "Salmos 86:13" },
  { texto: "Mas tú, Señor, Dios misericordioso y clemente, lento para la ira, y grande en misericordia y verdad.", referencia: "Salmos 86:15" },
  { texto: "Mírame, y ten misericordia de mí; da tu poder a tu siervo.", referencia: "Salmos 86:16" },
  
  // Diciembre (31 días)
  { texto: "Su cimiento está en el monte santo.", referencia: "Salmos 87:1" },
  { texto: "Ama Jehová las puertas de Sion más que todas las moradas de Jacob.", referencia: "Salmos 87:2" },
  { texto: "Cosas gloriosas se han dicho de ti, ciudad de Dios.", referencia: "Salmos 87:3" },
  { texto: "Yo me acordaré de Rahab y de Babilonia entre los que me conocen.", referencia: "Salmos 87:4" },
  { texto: "Y de Sion se dirá: Este y aquél han nacido en ella, y el Altísimo mismo la establecerá.", referencia: "Salmos 87:5" },
  { texto: "Jehová contará al inscribir a los pueblos: Este nació allí.", referencia: "Salmos 87:6" },
  { texto: "Y cantores y tañedores en ella dirán: Todas mis fuentes están en ti.", referencia: "Salmos 87:7" },
  { texto: "Oh Jehová, Dios de mi salvación, día y noche clamo delante de ti.", referencia: "Salmos 88:1" },
  { texto: "Llegue mi oración a tu presencia; inclina tu oído a mi clamor.", referencia: "Salmos 88:2" },
  { texto: "Porque mi alma está hastiada de males, y mi vida cercana al Seol.", referencia: "Salmos 88:3" },
  { texto: "Las misericordias de Jehová cantaré perpetuamente.", referencia: "Salmos 89:1" },
  { texto: "De generación en generación haré notoria tu fidelidad con mi boca.", referencia: "Salmos 89:1" },
  { texto: "Porque dije: Para siempre será edificada misericordia.", referencia: "Salmos 89:2" },
  { texto: "He hecho pacto con mi escogido; he jurado a David mi siervo.", referencia: "Salmos 89:3" },
  { texto: "Para siempre confirmaré tu descendencia, y edificaré tu trono por todas las generaciones.", referencia: "Salmos 89:4" },
  { texto: "Celebrarán los cielos tus maravillas, oh Jehová.", referencia: "Salmos 89:5" },
  { texto: "Bienaventurado el pueblo que sabe aclamarte; andará, oh Jehová, a la luz de tu rostro.", referencia: "Salmos 89:15" },
  { texto: "En tu nombre se alegrará todo el día, y en tu justicia será enaltecido.", referencia: "Salmos 89:16" },
  { texto: "Porque tú eres la gloria de su potencia.", referencia: "Salmos 89:17" },
  { texto: "Porque de Jehová es nuestro escudo, y nuestro rey es del Santo de Israel.", referencia: "Salmos 89:18" },
  { texto: "Hallé a David mi siervo; lo ungí con mi santa unción.", referencia: "Salmos 89:20" },
  { texto: "Mi mano estará siempre con él, mi brazo también lo fortalecerá.", referencia: "Salmos 89:21" },
  { texto: "Mi verdad y mi misericordia estarán con él, y en mi nombre será exaltado su poder.", referencia: "Salmos 89:24" },
  { texto: "Él me clamará: Mi padre eres tú, mi Dios, y la roca de mi salvación.", referencia: "Salmos 89:26" },
  { texto: "Para siempre le conservaré mi misericordia, y mi pacto será firme con él.", referencia: "Salmos 89:28" },
  { texto: "Señor, tú nos has sido refugio de generación en generación.", referencia: "Salmos 90:1" },
  { texto: "Antes que naciesen los montes y formases la tierra y el mundo, desde el siglo y hasta el siglo, tú eres Dios.", referencia: "Salmos 90:2" },
  { texto: "Porque mil años delante de tus ojos son como el día de ayer, que pasó.", referencia: "Salmos 90:4" },
  { texto: "Enséñanos de tal modo a contar nuestros días, que traigamos al corazón sabiduría.", referencia: "Salmos 90:12" },
  { texto: "Sácianos de mañana de tu misericordia, y cantaremos y nos alegraremos todos nuestros días.", referencia: "Salmos 90:14" },
  { texto: "Sea la luz de Jehová nuestro Dios sobre nosotros, y confirma sobre nosotros la obra de nuestras manos.", referencia: "Salmos 90:17" }
];

// Función para obtener el versículo del día (usando zona horaria de Chile)
export const getVersiculoDelDia = (): Versiculo => {
  const now = new Date();
  // Crear una fecha en zona horaria de Chile (UTC-3)
  const offset = -3 * 60; // UTC-3 en minutos
  const chileTime = new Date(now.getTime() + (offset + now.getTimezoneOffset()) * 60000);
  
  const diaDelAno = Math.floor((chileTime.getTime() - new Date(chileTime.getFullYear(), 0, 0).getTime()) / 86400000);
  const indice = diaDelAno % versiculos.length;
  return versiculos[indice];
};
